# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-24 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninterne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echeance',
            name='operation_date',
            field=models.DateField(null=True),
        ),
    ]
