# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=6)),
                ('cyclos_id', models.CharField(max_length=30)),
                ('cyclos_name', models.CharField(max_length=150)),
                ('cyclos_account_number', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'beneficiaire',
            },
        ),
    ]
