# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=6, unique=True)),
                ('answer', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'security_answer',
            },
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('predefined', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'security_question',
            },
        ),
        migrations.AddField(
            model_name='securityanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cel.SecurityQuestion'),
        ),
    ]
