# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 09:13
from __future__ import unicode_literals

from django.db import migrations


def populate_predefined_questions(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    SecurityQuestion = apps.get_model("cel", "SecurityQuestion")

    # Our predefined questions
    SecurityQuestion.objects.create(
        question="Quel est le nom de votre premier animal de compagnie ?", predefined=True)
    SecurityQuestion.objects.create(
        question="Quel est le nom de jeune fille de votre mère ?", predefined=True)


class Migration(migrations.Migration):

    dependencies = [
        ('cel', '0002_auto_20170216_1313'),
    ]

    operations = [
        migrations.RunPython(populate_predefined_questions),
    ]
