# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-23 14:14
from __future__ import unicode_literals

from django.db import migrations


def populate_predefined_questions(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    PredefinedSecurityQuestion = apps.get_model("cel", "PredefinedSecurityQuestion")

    # Our predefined questions
    PredefinedSecurityQuestion.objects.create(
        question="Quel est le nom de votre premier animal de compagnie ?", language='fr')
    PredefinedSecurityQuestion.objects.create(
        question="Quel est le nom de jeune fille de votre mère ?", language='fr')
    PredefinedSecurityQuestion.objects.create(
        question="Dans quelle ville êtes-vous né-e ?", language='fr')
    PredefinedSecurityQuestion.objects.create(
        question="Zer da zure lehen etxe animaliaren izena?", language='eu')
    PredefinedSecurityQuestion.objects.create(
        question="Zer da zure amaren ezkon-aitzineko deitura?", language='eu')
    PredefinedSecurityQuestion.objects.create(
        question="Zoin hiritan sortu zara?", language='eu')


class Migration(migrations.Migration):

    dependencies = [
        ('cel', '0005_predefinedsecurityquestion'),
    ]

    operations = [
        migrations.RunPython(populate_predefined_questions),
    ]
