# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-23 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cel', '0007_auto_20190923_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityanswer',
            name='question',
            field=models.CharField(default='question par défaut', max_length=150),
            preserve_default=False,
        ),
    ]
