# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-23 15:09
from __future__ import unicode_literals

from django.db import migrations


def copy_security_questions(apps, schema_editor):
    SecurityQuestion = apps.get_model("cel", "SecurityQuestion")
    SecurityAnswer = apps.get_model("cel", "SecurityAnswer")

    for answer in SecurityAnswer.objects.all():
        answer.question = answer.question_fk.question
        answer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cel', '0008_securityanswer_question'),
    ]

    operations = [
        migrations.RunPython(copy_security_questions),
    ]
