# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-23 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cel', '0009_copy_security_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityanswer',
            name='question_fk',
        ),
        migrations.DeleteModel(
            name='SecurityQuestion',
        ),
    ]
