# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-03 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cel', '0011_auto_20191001_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMandat',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_compte_debiteur', models.CharField(max_length=9)),
                ('nom_debiteur', models.CharField(max_length=150)),
                ('numero_compte_crediteur', models.CharField(max_length=9)),
                ('nom_crediteur', models.CharField(max_length=150)),
                ('statut', models.CharField(choices=[('ATT', 'En attente de validation'), ('VAL', 'Validé'), ('REF', 'Refusé'), ('REV', 'Révoqué')], default='ATT', max_length=3)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical mandat',
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
