# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-17 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cel', '0012_historicalmandat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdherentParticulier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AdherentTouriste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
