# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_token', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='token',
            new_name='dolibarr_token',
        ),
    ]
