# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_token', '0004_auto_20161003_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cyclos_auth_string',
            new_name='cyclos_token',
        ),
    ]
